"""empty message

Revision ID: e3bace098ddf
Revises: 
Create Date: 2025-05-11 08:28:16.711441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bace098ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_menu_item')
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('menu_item_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_item_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.create_foreign_key(None, 'menu_item', ['menu_item_id'], ['id'])

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('order_menu_item',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'menu_item_id')
    )
    # ### end Alembic commands ###
